correct indenting on circle config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,5 +1,4 @@
-defaults: &defaults
-  #working_directory: ./circleci
+defaults: &defaults #working_directory: ./circleci
   docker:
     - image: circleci/node:10.16
 
@@ -12,7 +11,7 @@ jobs:
       # Download and cache dependencies
       - restore_cache:
           keys:
-          - v1-dependencies-{{ checksum "package.json" }}
+            - v1-dependencies-{{ checksum "package.json" }}
       - run: npm install
       - save_cache:
           paths:
@@ -22,7 +21,7 @@ jobs:
           root: .
           paths:
             - node_modules
-      
+
   build:
     <<: *defaults
     steps:
@@ -44,40 +43,40 @@ jobs:
       - deploy:
           name: Deploy to GitHub Pages
           command: |
-              set -e
-              remote=$(git config remote.origin.url)
-              if [ ! -d "build" ]
-              then
-                  echo "build folder not found"
-                  exit 1
-              fi
-              mkdir gh-pages-branch
-              cd gh-pages-branch
-              git config --global user.email "rohilvg@gmail.com" > /dev/null 2>&1
-              git config --global user.name "Rohil Gupta" > /dev/null 2>&1
-              git init
-              git remote add --fetch origin "$remote"
-              if git rev-parse --verify origin/gh-pages > /dev/null 2>&1
-              then
-                  git checkout gh-pages
-                  git rm -rf .
-              else
-                  git checkout --orphan gh-pages
-              fi
-              cp -a "../build/." .
-              git add -A
-              git commit --allow-empty -m "Deploy to GitHub pages [ci skip]"
-              git push --force --quiet origin gh-pages > /dev/null 2>&1
-              cd ..
-              rm -rf gh-pages-branch
-              echo "Finished GitHub pages Deployment!"
+            set -e
+            remote=$(git config remote.origin.url)
+            if [ ! -d "build" ]
+            then
+                echo "build folder not found"
+                exit 1
+            fi
+            mkdir gh-pages-branch
+            cd gh-pages-branch
+            git config --global user.email "rohilvg@gmail.com" > /dev/null 2>&1
+            git config --global user.name "Rohil Gupta" > /dev/null 2>&1
+            git init
+            git remote add --fetch origin "$remote"
+            if git rev-parse --verify origin/gh-pages > /dev/null 2>&1
+            then
+                git checkout gh-pages
+                git rm -rf .
+            else
+                git checkout --orphan gh-pages
+            fi
+            cp -a "../build/." .
+            git add -A
+            git commit --allow-empty -m "Deploy to GitHub pages [ci skip]"
+            git push --force --quiet origin gh-pages > /dev/null 2>&1
+            cd ..
+            rm -rf gh-pages-branch
+            echo "Finished GitHub pages Deployment!"
 
 workflows:
   version: 2
   build_accept_deploy:
     jobs:
       - prepare
-      - build
+      - build:
           requires:
             - prepare
       - deploy-to-github:
